### ISSUE TITLE
`step!` functionality

### ISSUE THREAD

**Issue by rconnorjohnstone** [JuliaSpace/SatelliteToolboxSgp4.jl#2]
In the previous version of `SatelliteToolbox`, prior to the splitting of all the submodules, it was possible to propagate a TLE using a function `step!` which could be called multiple times and would overwrite the position of the satellite each time. Now there's just the `sgp4!` function, which doesn't seem to overwrite the state. If I call it twice, on the same sgp4d object with the same propagation time, I currently get the same answer both times. Is there a way to recover the old functionality? Where calling once with `1` would propagate it for one minute, then again with `1` would propagate it one *more* minute, etc.?

Alternatively, I only need the intermediate states of the propagation. So perhaps there's a way to interpolate with this new function?

**Comment by ronisbr** [comment]
Hi @rconnorjohnstone !

I think you were used to the propagator API in SatelliteToolbox. There is the same functionality in the package [SatelliteToolboxPropagators.jl](https://github.com/JuliaSpace/SatelliteToolboxPropagators.jl), where you can use `Propagators.step!`. In this case, the API is the same as you were using (including the dimensions).
